import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";
import { createApp } from "../server/app";
import { employeeId, ids } from "../server/seed";

test("employee login setup, scoped resets, and self-service password changes", async () => {
  process.env.DEMO_PASSWORD = "demo-test-password-2026";
  process.env.PLATFORM_OWNER_PASSWORD = "owner-test-password-2026";
  const {app,db} = await createApp({memory:true,demo:true});
  const http = app.getHttpAdapter().getInstance();
  const firm = request.agent(http);
  const company = request.agent(http);
  const hr = request.agent(http);
  const manager = request.agent(http);
  const employee = request.agent(http);
  const other = request.agent(http);
  const id = employeeId(3);
  const target = `/api/employees/${id}/login`;
  try {
    assert.equal((await request(http).get(target)).status,401);
    const f = await firm.post("/api/session").send({email:"admin@meridian.test",password:process.env.DEMO_PASSWORD});
    const c = await company.post("/api/session").send({email:"company@meridian.test",password:process.env.DEMO_PASSWORD});
    const m = await manager.post("/api/session").send({email:"manager@meridian.test",password:process.env.DEMO_PASSWORD});
    const o = await other.post("/api/session").send({email:"other@example.test",password:process.env.DEMO_PASSWORD});
    assert.equal(f.status,200); assert.equal(c.status,200); assert.equal(m.status,200); assert.equal(o.status,200);
    const hrUser = await firm.post("/api/users").set("X-CSRF-Token",f.body.csrf).send({name:"HR Tester",email:"hr-tester@example.test",password:"hr-tester-password-2026",employeeId:null});
    assert.equal(hrUser.status,201,JSON.stringify(hrUser.body));
    const hrGrant = await firm.post("/api/access").set("X-CSRF-Token",f.body.csrf).send({userId:hrUser.body.id,role:"hr",companyId:ids.a,branchId:null});
    assert.equal(hrGrant.status,201,JSON.stringify(hrGrant.body));
    const h = await hr.post("/api/session").send({email:"hr-tester@example.test",password:"hr-tester-password-2026"});
    assert.equal(h.status,200,JSON.stringify(h.body));
    assert.equal((await manager.get(target)).status,403);
    assert.equal((await other.get(target)).status,404);
    assert.equal((await company.get(`/api/employees/${employeeId(20)}/login`)).status,404);
    const legacy = await firm.get(`/api/employees/${employeeId(1)}/login`);
    assert.equal(legacy.status,200);
    assert.equal(legacy.body.needsEmailSync,true);
    assert.equal(legacy.body.loginReady,false);
    assert.equal((await firm.post(`/api/employees/${employeeId(1)}/login`).set("X-CSRF-Token",f.body.csrf).send({password:"aligned-password-2026"})).status,200);
    assert.equal((await firm.get(`/api/employees/${employeeId(1)}/login`)).body.loginReady,true);
    assert.equal((await request(http).post("/api/session").send({email:"employee1@example.test",password:"aligned-password-2026"})).status,200);
    const initial = await firm.get(target);
    assert.equal(initial.status,200,JSON.stringify(initial.body));
    assert.equal(initial.body.workEmail,"employee3@example.test");
    assert.equal(initial.body.loginReady,false);
    assert.equal(Object.hasOwn(initial.body,"password"),false);
    assert.equal((await firm.post(target).send({password:"initial-password-2026"})).status,403);
    const created = await firm.post(target).set("X-CSRF-Token",f.body.csrf).send({password:"initial-password-2026"});
    assert.equal(created.status,201,JSON.stringify(created.body));
    assert.equal((await company.get(target)).body.loginReady,true);
    const signIn = await employee.post("/api/session").send({email:"employee3@example.test",password:"initial-password-2026"});
    assert.equal(signIn.status,200,JSON.stringify(signIn.body));
    const selfRows = await employee.get("/api/employees");
    assert.deepEqual(selfRows.body.map((row:any)=>row.id),[id]);
    assert.equal((await employee.get(target)).status,403);
    const wrong = await employee.patch("/api/session/password").set("X-CSRF-Token",signIn.body.csrf).send({currentPassword:"wrong-password-2026",newPassword:"changed-password-2026"});
    assert.equal(wrong.status,403);
    const changed = await employee.patch("/api/session/password").set("X-CSRF-Token",signIn.body.csrf).send({currentPassword:"initial-password-2026",newPassword:"changed-password-2026"});
    assert.equal(changed.status,200,JSON.stringify(changed.body));
    assert.equal((await employee.get("/api/session")).status,401);
    assert.equal((await employee.post("/api/session").send({email:"employee3@example.test",password:"initial-password-2026"})).status,401);
    assert.equal((await employee.post("/api/session").send({email:"employee3@example.test",password:"changed-password-2026"})).status,200);
    const reset = await company.post(target).set("X-CSRF-Token",c.body.csrf).send({password:"admin-reset-password-2026"});
    assert.equal(reset.status,200,JSON.stringify(reset.body));
    assert.equal((await employee.get("/api/session")).status,401);
    assert.equal((await employee.post("/api/session").send({email:"employee3@example.test",password:"admin-reset-password-2026"})).status,200);
    assert.equal((await firm.get(`/api/employees/${employeeId(2)}/login`)).body.managedSeparately,true);
    const adminLinked = await firm.post(`/api/employees/${employeeId(2)}/login`).set("X-CSRF-Token",f.body.csrf).send({password:"cannot-reset-manager-2026"});
    assert.equal(adminLinked.status,409);
    const hrReset = await hr.post(target).set("X-CSRF-Token",h.body.csrf).send({password:"hr-reset-password-2026"});
    assert.equal(hrReset.status,200,JSON.stringify(hrReset.body));
    assert.equal((await employee.post("/api/session").send({email:"employee3@example.test",password:"hr-reset-password-2026"})).status,200);
    const edited = await hr.patch(`/api/employees/${id}`).set("X-CSRF-Token",h.body.csrf).send({name:"Updated Employee",email:"updated-employee3@example.test",department:"Operations",designation:"Senior Officer",employmentType:"Permanent",joinedOn:"2025-05-01"});
    assert.equal(edited.status,200,JSON.stringify(edited.body));
    assert.equal(edited.body.employee.email,"updated-employee3@example.test");
    assert.equal(edited.body.employee.department,"Operations");
    assert.equal((await employee.get("/api/session")).status,401);
    assert.equal((await employee.post("/api/session").send({email:"employee3@example.test",password:"hr-reset-password-2026"})).status,401);
    assert.equal((await employee.post("/api/session").send({email:"updated-employee3@example.test",password:"hr-reset-password-2026"})).status,200);
    assert.equal((await company.patch(`/api/employees/${employeeId(20)}`).set("X-CSRF-Token",c.body.csrf).send({name:"Cross company"})).status,404);
    assert.equal((await company.patch(`/api/employees/${id}`).set("X-CSRF-Token",c.body.csrf).send({status:"inactive"})).status,200);
    assert.equal((await employee.get("/api/session")).status,401);
    assert.equal((await employee.post("/api/session").send({email:"updated-employee3@example.test",password:"hr-reset-password-2026"})).status,401);
    assert.equal((await company.patch(`/api/employees/${id}`).set("X-CSRF-Token",c.body.csrf).send({status:"active"})).status,200);
    assert.equal((await employee.post("/api/session").send({email:"updated-employee3@example.test",password:"hr-reset-password-2026"})).status,200);
  } finally { await app.close(); await db.close(); }
});
