import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";
import { createApp } from "../server/app";
import { ids } from "../server/seed";
import { detectEmployeeFileFormat, parseEmployeeCsv } from "../src/EmployeeImport";

test("CSV parser handles quotes, required headers and malformed rows",()=>{
  const rows=parseEmployeeCsv('code,name,email,department,designation,employmentType,joinedOn\nE77,"Jane, Doe",jane@example.test,HR,Officer,Permanent,2026-01-02');
  assert.equal(rows[0].name,"Jane, Doe");
  assert.throws(()=>parseEmployeeCsv('code,name\nA,A'),/Missing columns/);
  assert.equal(detectEmployeeFileFormat(new TextEncoder().encode('PK\u0003\u0004Index/Document.iwa')),"numbers");
  assert.equal(detectEmployeeFileFormat(new TextEncoder().encode('code,name\nA,A')),"csv");
});

test("platform owner, tenant isolation, import and limits",async()=>{
  process.env.DEMO_PASSWORD="demo-test-password-2026";
  process.env.PLATFORM_OWNER_PASSWORD="owner-test-password-2026";
  const {app,db}=await createApp({memory:true,demo:true});
  const http=request(app.getHttpAdapter().getInstance());
  const owner=request.agent(app.getHttpAdapter().getInstance());
  const firm=request.agent(app.getHttpAdapter().getInstance());
  try{
    assert.equal((await http.get("/api/platform/overview")).status,401);
    const login=await owner.post("/api/session").send({email:"owner@ascommunications.test",password:process.env.PLATFORM_OWNER_PASSWORD});
    assert.equal(login.status,200,JSON.stringify(login.body));
    const csrf=login.body.csrf;
    const overview=await owner.get("/api/platform/overview");
    assert.equal(overview.status,200,JSON.stringify(overview.body));
    assert.ok(overview.body.totals.companies>=3);
    assert.equal((await owner.get("/api/employees")).status,403);
    assert.equal((await owner.post("/api/platform/tenants").send({})).status,403); // CSRF
    const tenant=await owner.post("/api/platform/tenants").set("X-CSRF-Token",csrf).send({firmName:"Test Firm",adminName:"Test Admin",adminEmail:"test-admin@example.test",adminPassword:"tenant-test-password-2026",employeeLimit:2});
    assert.equal(tenant.status,201,JSON.stringify(tenant.body));
    const company=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:tenant.body.id,name:"Test Company",code:"TEST",employeeLimit:1});
    assert.equal(company.status,201,JSON.stringify(company.body));
    const other=await firm.post("/api/session").send({email:"test-admin@example.test",password:"tenant-test-password-2026"});
    assert.equal(other.status,200,JSON.stringify(other.body));
    const otherCsrf=other.body.csrf;
    assert.equal((await firm.get(`/api/platform/companies/${ids.a}/employees`)).status,403);
    assert.equal((await firm.get(`/api/employees?companyId=${ids.a}`)).body.length,0);
    const firmCreatedCompany=await firm.post("/api/companies").set("X-CSRF-Token",otherCsrf).send({name:"Second Company",code:"SECOND"});
    assert.equal(firmCreatedCompany.status,201,JSON.stringify(firmCreatedCompany.body));
    const branch=await firm.post("/api/branches").set("X-CSRF-Token",otherCsrf).send({companyId:company.body.id,name:"Test Branch"});
    assert.equal(branch.status,201,JSON.stringify(branch.body));
    const renamed=await firm.patch(`/api/branches/${branch.body.id}`).set("X-CSRF-Token",otherCsrf).send({name:"Renamed Branch"});
    assert.equal(renamed.status,200,JSON.stringify(renamed.body));
    assert.equal(renamed.body.name,"Renamed Branch");
    assert.equal((await firm.patch(`/api/branches/${branch.body.id}`).send({name:"No CSRF"})).status,403);
    const spare=await firm.post("/api/branches").set("X-CSRF-Token",otherCsrf).send({companyId:company.body.id,name:"Unused Branch"});
    assert.equal(spare.status,201);
    assert.equal((await firm.delete(`/api/branches/${spare.body.id}`).set("X-CSRF-Token",otherCsrf).send({})).status,200);
    assert.equal((await firm.delete(`/api/branches/${ids.a1}`).set("X-CSRF-Token",otherCsrf).send({})).status,404);
    const row={code:"T001",name:"Test Employee",email:"test.employee@example.test",department:"HR",designation:"Officer",employmentType:"Permanent",joinedOn:"2026-01-02"};
    const imported=await firm.post("/api/employees/import").set("X-CSRF-Token",otherCsrf).send({companyId:company.body.id,branchId:branch.body.id,source:"csv",rows:[row]});
    assert.equal(imported.status,201,JSON.stringify(imported.body));
    assert.equal(imported.body.imported,1);
    const blockedDelete=await firm.delete(`/api/branches/${branch.body.id}`).set("X-CSRF-Token",otherCsrf).send({});
    assert.equal(blockedDelete.status,409,JSON.stringify(blockedDelete.body));
    const over=await firm.post("/api/employees/import").set("X-CSRF-Token",otherCsrf).send({companyId:company.body.id,branchId:branch.body.id,source:"csv",rows:[{...row,code:"T002"}]});
    assert.notEqual(over.status,201);
    const added=(await firm.get("/api/employees")).body.find((e:any)=>e.code==="T001");
    const archived=await firm.patch(`/api/employees/${added.id}`).set("X-CSRF-Token",otherCsrf).send({status:"inactive"});
    assert.equal(archived.status,200,JSON.stringify(archived.body));
    assert.equal(archived.body.employee.status,"inactive");
    const replacement=await firm.post("/api/employees/import").set("X-CSRF-Token",otherCsrf).send({companyId:company.body.id,branchId:branch.body.id,source:"csv",rows:[{...row,code:"T002",email:"replacement@example.test"}]});
    assert.equal(replacement.status,201,JSON.stringify(replacement.body));
    assert.equal((await firm.patch(`/api/employees/${added.id}`).set("X-CSRF-Token",otherCsrf).send({status:"active"})).status,409);
    const capacityFirm=await owner.post("/api/platform/tenants").set("X-CSRF-Token",csrf).send({firmName:"Capacity Firm",adminName:"Capacity Admin",adminEmail:"capacity-admin@example.test",adminPassword:"capacity-admin-password-2026",employeeLimit:50});
    assert.equal(capacityFirm.status,201,JSON.stringify(capacityFirm.body));
    const first=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:capacityFirm.body.id,name:"First Company",code:"FIRST",employeeLimit:30});
    assert.equal(first.status,201,JSON.stringify(first.body));
    const adminFirm=await owner.post("/api/platform/tenants").set("X-CSRF-Token",csrf).send({firmName:"Admin Firm",adminName:"Admin Firm Owner",adminEmail:"admin-firm-owner@example.test",adminPassword:"admin-firm-owner-password",employeeLimit:10});
    assert.equal(adminFirm.status,201,JSON.stringify(adminFirm.body));
    const adminCompany=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:adminFirm.body.id,name:"Admin Company",code:"ADMIN",employeeLimit:5,companyAdmin:{name:"Company Owner",email:"company-owner@example.test",password:"company-owner-password"},hrAdmin:{name:"HR Owner",email:"hr-owner@example.test",password:"hr-owner-password-2026"}});
    assert.equal(adminCompany.status,201,JSON.stringify(adminCompany.body));
    const listAdmins=await owner.get(`/api/platform/tenants/${adminFirm.body.id}/administrators`);
    assert.equal(listAdmins.status,200,JSON.stringify(listAdmins.body));
    assert.equal(listAdmins.body.length,3);
    assert.equal(listAdmins.body.find((u:any)=>u.role==="company_admin").name,"Company Owner");
    const companyAdmin=request.agent(app.getHttpAdapter().getInstance());
    const companyAdminLogin=await companyAdmin.post("/api/session").send({email:"company-owner@example.test",password:"company-owner-password"});
    assert.equal(companyAdminLogin.status,200);
    const companyBranch=await companyAdmin.post("/api/branches").set("X-CSRF-Token",companyAdminLogin.body.csrf).send({companyId:adminCompany.body.id,name:"Admin Branch"});
    assert.equal(companyBranch.status,201,JSON.stringify(companyBranch.body));
    assert.equal((await companyAdmin.patch(`/api/branches/${companyBranch.body.id}`).set("X-CSRF-Token",companyAdminLogin.body.csrf).send({name:"Admin Branch Renamed"})).status,200);
    assert.equal((await companyAdmin.patch(`/api/branches/${branch.body.id}`).set("X-CSRF-Token",companyAdminLogin.body.csrf).send({name:"Cross tenant"})).status,404);
    assert.equal((await companyAdmin.delete(`/api/branches/${companyBranch.body.id}`).set("X-CSRF-Token",companyAdminLogin.body.csrf).send({})).status,200);
    const companyAdminUser=listAdmins.body.find((u:any)=>u.role==="company_admin");
    assert.equal((await companyAdmin.patch(`/api/admin-users/${companyAdminUser.id}`).set("X-CSRF-Token",companyAdminLogin.body.csrf).send({name:"Unauthorized self-edit"})).status,403);
    const adminFirmOwner=request.agent(app.getHttpAdapter().getInstance());
    const adminFirmOwnerLogin=await adminFirmOwner.post("/api/session").send({email:"admin-firm-owner@example.test",password:"admin-firm-owner-password"});
    assert.equal(adminFirmOwnerLogin.status,200);
    const firmOwnerSession=await adminFirmOwner.get("/api/session");
    const editedAdmin=await adminFirmOwner.patch(`/api/admin-users/${companyAdminUser.id}`).set("X-CSRF-Token",adminFirmOwnerLogin.body.csrf).send({name:"Renamed Company Owner",email:"renamed-company-owner@example.test",newPassword:"renamed-owner-password-2026"});
    assert.equal(editedAdmin.status,200,JSON.stringify(editedAdmin.body));
    assert.equal((await companyAdmin.get("/api/session")).status,401);
    assert.equal((await firm.patch(`/api/admin-users/${companyAdminUser.id}`).set("X-CSRF-Token",otherCsrf).send({name:"Wrong Firm"})).status,404);
    assert.equal((await adminFirmOwner.patch(`/api/admin-users/${firmOwnerSession.body.user.id}`).set("X-CSRF-Token",adminFirmOwnerLogin.body.csrf).send({name:"Self"})).status,403);
    const adminGrantList=await adminFirmOwner.get("/api/access");
    const companyAdminGrant=adminGrantList.body.grants.find((g:any)=>g.user_id===companyAdminUser.id&&g.role==="company_admin");
    assert.ok(companyAdminGrant);
    assert.equal((await adminFirmOwner.delete(`/api/access/${companyAdminGrant.id}`).set("X-CSRF-Token",adminFirmOwnerLogin.body.csrf).send({})).status,200);
    assert.equal((await request(app.getHttpAdapter().getInstance()).post("/api/session").send({email:"renamed-company-owner@example.test",password:"renamed-owner-password-2026"})).status,401);
    assert.equal(listAdmins.body.find((u:any)=>u.role==="hr").email,"hr-owner@example.test");
    assert.ok(listAdmins.body.every((u:any)=>!Object.hasOwn(u,"password")&&!Object.hasOwn(u,"password_hash")));
    assert.equal((await firm.get(`/api/platform/tenants/${adminFirm.body.id}/administrators`)).status,403);
    const hr=request.agent(app.getHttpAdapter().getInstance());
    const hrLogin=await hr.post("/api/session").send({email:"hr-owner@example.test",password:"hr-owner-password-2026"});
    assert.equal(hrLogin.status,200,JSON.stringify(hrLogin.body));
    assert.equal((await hr.get(`/api/employees?companyId=${ids.a}`)).status,403);
    const hrUser=listAdmins.body.find((u:any)=>u.role==="hr");
    const changed=await owner.patch(`/api/platform/users/${hrUser.id}`).set("X-CSRF-Token",csrf).send({name:"Updated HR Owner",email:"updated-hr-owner@example.test",newPassword:"new-hr-owner-password-2026"});
    assert.equal(changed.status,200,JSON.stringify(changed.body));
    assert.equal((await hr.get("/api/session")).status,401);
    assert.equal((await hr.post("/api/session").send({email:"updated-hr-owner@example.test",password:"hr-owner-password-2026"})).status,401);
    assert.equal((await hr.post("/api/session").send({email:"updated-hr-owner@example.test",password:"new-hr-owner-password-2026"})).status,200);
    const updatedAdmins=await owner.get(`/api/platform/tenants/${adminFirm.body.id}/administrators`);
    assert.equal(updatedAdmins.body.find((u:any)=>u.id===hrUser.id).name,"Updated HR Owner");
    assert.equal((await firm.patch(`/api/platform/users/${hrUser.id}`).set("X-CSRF-Token",otherCsrf).send({name:"Intruder"})).status,403);
    const duplicateAdmin=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:adminFirm.body.id,name:"Bad Admin Company",code:"BAD",employeeLimit:1,companyAdmin:{name:"One",email:"same@example.test",password:"same-password-2026"},hrAdmin:{name:"Two",email:"same@example.test",password:"different-password-2026"}});
    assert.equal(duplicateAdmin.status,400);
    const tooMany=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:capacityFirm.body.id,name:"Second Company",code:"SECOND",employeeLimit:25});
    assert.equal(tooMany.status,409);
    assert.match(tooMany.body.error,/Only 20 employee slots remain/);
    const second=await owner.post("/api/platform/companies").set("X-CSRF-Token",csrf).send({tenantId:capacityFirm.body.id,name:"Second Company",code:"SECOND",employeeLimit:20});
    assert.equal(second.status,201,JSON.stringify(second.body));
    const lowerFirm=await owner.patch(`/api/platform/tenants/${capacityFirm.body.id}`).set("X-CSRF-Token",csrf).send({employeeLimit:49});
    assert.equal(lowerFirm.status,409);
    assert.match(lowerFirm.body.error,/at least 50/);
    const raiseCompany=await owner.patch(`/api/platform/companies/${second.body.id}`).set("X-CSRF-Token",csrf).send({employeeLimit:21});
    assert.equal(raiseCompany.status,409);
    await assert.rejects(db.owner(q=>q.query("UPDATE platform_company_limits SET employee_limit=21 WHERE company_id=$1",[second.body.id])),{code:"23514"});
    const capacityOverview=await owner.get("/api/platform/overview");
    assert.equal(capacityOverview.body.companies.filter((c:any)=>c.tenant_id===capacityFirm.body.id).length,2);
    await db.init(); // repeated hosted-style migrations must preserve existing allocations
    const suspended=await owner.patch(`/api/platform/tenants/${tenant.body.id}`).set("X-CSRF-Token",csrf).send({status:"suspended"});
    assert.equal(suspended.status,200,JSON.stringify(suspended.body));
    assert.equal((await firm.get("/api/organization")).status,401);
  }finally{await app.close();await db.close()}
});
